## Sentiment Analysis

In [1]:
import pandas as pd
import numpy as np
from transformers import pipeline

In [2]:
books = pd.read_csv("../data/processed/book_categorized.csv")
books.head()

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitles,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction
2,9780006178736,0006178731,Rage of angels,NaN,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction
3,9780006280897,0006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Nonfiction
4,9780006280934,0006280935,The Problem of Pain,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction

In [3]:

classifier = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base", return_all_scores=True, device=1)
classifier("I love this!",top_k=None)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: j-hartmann/emotion-english-distilroberta-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

[{'label': 'joy', 'score': 0.9771687984466553},
 {'label': 'surprise', 'score': 0.008528691716492176},
 {'label': 'neutral', 'score': 0.005764589179307222},
 {'label': 'anger', 'score': 0.004419787786900997},
 {'label': 'sadness', 'score': 0.002092392183840275},
 {'label': 'disgust', 'score': 0.001611991785466671},
 {'label': 'fear', 'score': 0.0004138525982853025}]

In [4]:
classifier("Mr.Stark this smells like a new car in here", top_k=None)

[{'label': 'neutral', 'score': 0.6717337369918823},
 {'label': 'surprise', 'score': 0.24689394235610962},
 {'label': 'joy', 'score': 0.05578450486063957},
 {'label': 'sadness', 'score': 0.010191187262535095},
 {'label': 'disgust', 'score': 0.00737769203260541},
 {'label': 'anger', 'score': 0.005068677011877298},
 {'label': 'fear', 'score': 0.002950346330180764}]

In [5]:
classifier("Mr.Stark  i don't feel so good", top_k=None)

[{'label': 'sadness', 'score': 0.8909273147583008},
 {'label': 'joy', 'score': 0.06010271981358528},
 {'label': 'surprise', 'score': 0.03766956552863121},
 {'label': 'neutral', 'score': 0.007450808770954609},
 {'label': 'fear', 'score': 0.0016921063652262092},
 {'label': 'anger', 'score': 0.0016191054601222277},
 {'label': 'disgust', 'score': 0.0005384085816331208}]

In [6]:
classifier("I am Batman", top_k=None)

[{'label': 'neutral', 'score': 0.8142164349555969},
 {'label': 'surprise', 'score': 0.09812664240598679},
 {'label': 'fear', 'score': 0.03162233531475067},
 {'label': 'joy', 'score': 0.03005947731435299},
 {'label': 'sadness', 'score': 0.014958278276026249},
 {'label': 'anger', 'score': 0.007858430966734886},
 {'label': 'disgust', 'score': 0.0031584312673658133}]

In [7]:
classifier("We are venom", top_k=None)

[{'label': 'anger', 'score': 0.797040581703186},
 {'label': 'disgust', 'score': 0.1110977753996849},
 {'label': 'neutral', 'score': 0.06327743828296661},
 {'label': 'fear', 'score': 0.016143765300512314},
 {'label': 'sadness', 'score': 0.008029772900044918},
 {'label': 'surprise', 'score': 0.0031558272894471884},
 {'label': 'joy', 'score': 0.0012549057137221098}]

In [8]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [9]:
classifier(books["description"][0], top_k=None)

[{'label': 'fear', 'score': 0.654840350151062},
 {'label': 'neutral', 'score': 0.1698523312807083},
 {'label': 'sadness', 'score': 0.11640936881303787},
 {'label': 'surprise', 'score': 0.020700648427009583},
 {'label': 'disgust', 'score': 0.01910071074962616},
 {'label': 'joy', 'score': 0.015161431394517422},
 {'label': 'anger', 'score': 0.003935148473829031}]

In [10]:
# lets do this for each sentences in the description column and add it as a new column in the dataframe
sentences  = books["description"][0].split(".")
predictions = classifier(sentences, top_k=None)

In [11]:
predictions[0]

[{'label': 'surprise', 'score': 0.7296019792556763},
 {'label': 'neutral', 'score': 0.14038611948490143},
 {'label': 'fear', 'score': 0.06816229224205017},
 {'label': 'joy', 'score': 0.04794260114431381},
 {'label': 'anger', 'score': 0.009156369604170322},
 {'label': 'disgust', 'score': 0.0026284789200872183},
 {'label': 'sadness', 'score': 0.002122164238244295}]

In [12]:
predictions[1]

[{'label': 'neutral', 'score': 0.4493708610534668},
 {'label': 'disgust', 'score': 0.2735908627510071},
 {'label': 'joy', 'score': 0.10908335447311401},
 {'label': 'sadness', 'score': 0.09362750500440598},
 {'label': 'anger', 'score': 0.04047826677560806},
 {'label': 'surprise', 'score': 0.026970183476805687},
 {'label': 'fear', 'score': 0.006879056338220835}]

In [13]:
predictions

[[{'label': 'surprise', 'score': 0.7296019792556763},
  {'label': 'neutral', 'score': 0.14038611948490143},
  {'label': 'fear', 'score': 0.06816229224205017},
  {'label': 'joy', 'score': 0.04794260114431381},
  {'label': 'anger', 'score': 0.009156369604170322},
  {'label': 'disgust', 'score': 0.0026284789200872183},
  {'label': 'sadness', 'score': 0.002122164238244295}],
 [{'label': 'neutral', 'score': 0.4493708610534668},
  {'label': 'disgust', 'score': 0.2735908627510071},
  {'label': 'joy', 'score': 0.10908335447311401},
  {'label': 'sadness', 'score': 0.09362750500440598},
  {'label': 'anger', 'score': 0.04047826677560806},
  {'label': 'surprise', 'score': 0.026970183476805687},
  {'label': 'fear', 'score': 0.006879056338220835}],
 [{'label': 'neutral', 'score': 0.6462154388427734},
  {'label': 'sadness', 'score': 0.24273377656936646},
  {'label': 'disgust', 'score': 0.04342271387577057},
  {'label': 'surprise', 'score': 0.028300553560256958},
  {'label': 'joy', 'score': 0.014211496338248253},
  {'label': 'fear', 'score': 0.01408410258591175},
  {'label': 'anger', 'score': 0.011031907983124256}],
 [{'label': 'fear', 'score': 0.9281682968139648},
  {'label': 'anger', 'score': 0.03219083696603775},
  {'label': 'neutral', 'score': 0.012808673083782196},
  {'label': 'sadness', 'score': 0.008756859228014946},
  {'label': 'surprise', 'score': 0.008597901090979576},
  {'label': 'disgust', 'score': 0.008431811816990376},
  {'label': 'joy', 'score': 0.0010455823503434658}],
 [{'label': 'sadness', 'score': 0.9671575427055359},
  {'label': 'neutral', 'score': 0.015104127116501331},
  {'label': 'disgust', 'score': 0.006480586249381304},
  {'label': 'fear', 'score': 0.005393980070948601},
  {'label': 'surprise', 'score': 0.0022869384847581387},
  {'label': 'anger', 'score': 0.001842886907979846},
  {'label': 'joy', 'score': 0.0017338756006211042}],
 [{'label': 'joy', 'score': 0.9327981472015381},
  {'label': 'disgust', 'score': 0.03771701827645302},
  {'label': 'neutral', 'score': 0.015891805291175842},
  {'label': 'sadness', 'score': 0.006444500293582678},
  {'label': 'anger', 'score': 0.005024965852499008},
  {'label': 'surprise', 'score': 0.001581205171532929},
  {'label': 'fear', 'score': 0.0005423059337772429}],
 [{'label': 'joy', 'score': 0.6528709530830383},
  {'label': 'neutral', 'score': 0.2542746365070343},
  {'label': 'surprise', 'score': 0.06808288395404816},
  {'label': 'sadness', 'score': 0.009908979758620262},
  {'label': 'disgust', 'score': 0.006512224208563566},
  {'label': 'anger', 'score': 0.004821305628865957},
  {'label': 'fear', 'score': 0.003529016626998782}],
 [{'label': 'neutral', 'score': 0.5494766235351562},
  {'label': 'sadness', 'score': 0.11169016361236572},
  {'label': 'disgust', 'score': 0.10400673002004623},
  {'label': 'surprise', 'score': 0.07876551896333694},
  {'label': 'anger', 'score': 0.0641336739063263},
  {'label': 'fear', 'score': 0.05136285349726677},
  {'label': 'joy', 'score': 0.040564440190792084}]]

In [14]:
sorted(predictions[0], key=lambda x: x["label"], reverse=True)

[{'label': 'surprise', 'score': 0.7296019792556763},
 {'label': 'sadness', 'score': 0.002122164238244295},
 {'label': 'neutral', 'score': 0.14038611948490143},
 {'label': 'joy', 'score': 0.04794260114431381},
 {'label': 'fear', 'score': 0.06816229224205017},
 {'label': 'disgust', 'score': 0.0026284789200872183},
 {'label': 'anger', 'score': 0.009156369604170322}]

In [10]:

emotion_labels = ["anger", "disgust", "fear", "joy", "neutral", "sadness", "surprise"]
isbn = []
emotion_score = {label: [] for label in emotion_labels}

def calculate_max_emotion_score(predictions):
    per_emotion_score = {label: [] for label in emotion_labels}
    for prediction in predictions:
        sorted_prediction = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_score[label].append(sorted_prediction[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_score.items()}

In [11]:
for i in range(20):
    isbn.append(books["isbn13"][i])
    sentences  = books["description"][i].split(".")
    predictions = classifier(sentences, top_k=None)
    max_Scores = calculate_max_emotion_score(predictions)
    for label in emotion_labels:
        emotion_score[label].append(max_Scores[label])

In [12]:
emotion_score

{'anger': [np.float64(0.0641336739063263),
  np.float64(0.6126195192337036),
  np.float64(0.0641336739063263),
  np.float64(0.35148394107818604),
  np.float64(0.08141249418258667),
  np.float64(0.23222479224205017),
  np.float64(0.5381840467453003),
  np.float64(0.0641336739063263),
  np.float64(0.30066978931427),
  np.float64(0.0641336739063263),
  np.float64(0.0641336739063263),
  np.float64(0.611575186252594),
  np.float64(0.10621575266122818),
  np.float64(0.0641336739063263),
  np.float64(0.07239256054162979),
  np.float64(0.09586359560489655),
  np.float64(0.16215912997722626),
  np.float64(0.0641336739063263),
  np.float64(0.08193843811750412),
  np.float64(0.2234606295824051)],
 'disgust': [np.float64(0.2735908627510071),
  np.float64(0.34828442335128784),
  np.float64(0.10400673002004623),
  np.float64(0.15072239935398102),
  np.float64(0.18449552357196808),
  np.float64(0.7271748781204224),
  np.float64(0.15585491061210632),
  np.float64(0.10400673002004623),
  np.float64(0.27948111295700073),
  np.float64(0.17792649567127228),
  np.float64(0.10400673002004623),
  np.float64(0.28044393658638),
  np.float64(0.1292049139738083),
  np.float64(0.10400673002004623),
  np.float64(0.11641576141119003),
  np.float64(0.025357685983181),
  np.float64(0.47978466749191284),
  np.float64(0.10400673002004623),
  np.float64(0.1571670025587082),
  np.float64(0.1628391593694687)],
 'fear': [np.float64(0.9281682968139648),
  np.float64(0.942527711391449),
  np.float64(0.9723208546638489),
  np.float64(0.3607065677642822),
  np.float64(0.0950433760881424),
  np.float64(0.05136285349726677),
  np.float64(0.7474275231361389),
  np.float64(0.40449726581573486),
  np.float64(0.9155240654945374),
  np.float64(0.05136285349726677),
  np.float64(0.05136285349726677),
  np.float64(0.9296880960464478),
  np.float64(0.9810059070587158),
  np.float64(0.9486446976661682),
  np.float64(0.953626275062561),
  np.float64(0.812282919883728),
  np.float64(0.05136285349726677),
  np.float64(0.05136285349726677),
  np.float64(0.9767546057701111),
  np.float64(0.8174950480461121)],
 'joy': [np.float64(0.9327981472015381),
  np.float64(0.7044221758842468),
  np.float64(0.7672383785247803),
  np.float64(0.2518808841705322),
  np.float64(0.040564440190792084),
  np.float64(0.043375834822654724),
  np.float64(0.8725656270980835),
  np.float64(0.040564440190792084),
  np.float64(0.040564440190792084),
  np.float64(0.040564440190792084),
  np.float64(0.36806851625442505),
  np.float64(0.040564440190792084),
  np.float64(0.5042048096656799),
  np.float64(0.9055342674255371),
  np.float64(0.5094084143638611),
  np.float64(0.003585195867344737),
  np.float64(0.040564440190792084),
  np.float64(0.7202298045158386),
  np.float64(0.550420880317688),
  np.float64(0.9299788475036621)],
 'neutral': [np.float64(0.6462154388427734),
  np.float64(0.8879395127296448),
  np.float64(0.5494766235351562),
  np.float64(0.7326849699020386),
  np.float64(0.8843896985054016),
  np.float64(0.6213918924331665),
  np.float64(0.7121939659118652),
  np.float64(0.5494766235351562),
  np.float64(0.8402893543243408),
  np.float64(0.8603722453117371),
  np.float64(0.9092973470687866),
  np.float64(0.5494766235351562),
  np.float64(0.714712381362915),
  np.float64(0.5684452056884766),
  np.float64(0.5494766235351562),
  np.float64(0.05131059139966965),
  np.float64(0.5494766235351562),
  np.float64(0.5494766235351562),
  np.float64(0.568198561668396),
  np.float64(0.6362952589988708)],
 'sadness': [np.float64(0.9671575427055359),
  np.float64(0.11169016361236572),
  np.float64(0.11169016361236572),
  np.float64(0.11169016361236572),
  np.float64(0.4758802652359009),
  np.float64(0.11169016361236572),
  np.float64(0.40800097584724426),
  np.float64(0.8202826380729675),
  np.float64(0.3544614315032959),
  np.float64(0.11169016361236572),
  np.float64(0.16030198335647583),
  np.float64(0.39219343662261963),
  np.float64(0.12254166603088379),
  np.float64(0.856201708316803),
  np.float64(0.8412135243415833),
  np.float64(0.8029152750968933),
  np.float64(0.17530861496925354),
  np.float64(0.11169016361236572),
  np.float64(0.11169016361236572),
  np.float64(0.42946577072143555)],
 'surprise': [np.float64(0.7296019792556763),
  np.float64(0.2525462806224823),
  np.float64(0.07876551896333694),
  np.float64(0.07876551896333694),
  np.float64(0.07876551896333694),
  np.float64(0.27190351486206055),
  np.float64(0.07876551896333694),
  np.float64(0.23448720574378967),
  np.float64(0.13561397790908813),
  np.float64(0.07876551896333694),
  np.float64(0.16445773839950562),
  np.float64(0.07876551896333694),
  np.float64(0.07876551896333694),
  np.float64(0.24593250453472137),
  np.float64(0.8030907511711121),
  np.float64(0.006833172868937254),
  np.float64(0.07876551896333694),
  np.float64(0.07876551896333694),
  np.float64(0.07876551896333694),
  np.float64(0.07876551896333694)]}

In [13]:
from tqdm import tqdm

emotion_labels = ["anger", "disgust", "fear", "joy", "neutral", "sadness", "surprise"]
isbn = []
emotion_score = {label: [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences  = books["description"][i].split(".")
    predictions = classifier(sentences, top_k=None)
    max_Scores = calculate_max_emotion_score(predictions)
    for label in emotion_labels:
        emotion_score[label].append(max_Scores[label])

  0%|          | 0/5197 [00:00<?, ?it/s]

100%|██████████| 5197/5197 [20:23<00:00,  4.25it/s]

In [14]:
emotions_df = pd.DataFrame(emotion_score)
emotions_df["isbn13"] = isbn

In [15]:
books = pd.merge(books, emotions_df, on="isbn13")
books.head()

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,...,title_and_subtitles,tagged_description,simple_categories,anger,disgust,fear,joy,neutral,sadness,surprise
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,...,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction,0.064134,0.273591,0.928168,0.932798,0.646215,0.967158,0.729602
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612620,0.348284,0.942528,0.704422,0.887940,0.111690,0.252546
2,9780006178736,0006178731,Rage of angels,NaN,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,...,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction,0.064134,0.104007,0.972321,0.767238,0.549477,0.111690,0.078766
3,9780006280897,0006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,...,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Nonfiction,0.351484,0.150722,0.360707,0.251881,0.732685,0.111690,0.078766
4,9780006280934,0006280935,The Problem of Pain,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,...,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction,0.081412,0.184496,0.095043,0.040564,0.884390,0.475880,0.078766

In [16]:
books.to_csv("../data/processed/book_categorized_with_emotions.csv", index=False)