## Vector Search

In [1]:
# Imports the utility to load raw text files into LangChain Document objects
from langchain_community.document_loaders import TextLoader 
# Imports the tool to break long documents into smaller, manageable chunks
from langchain_text_splitters import CharacterTextSplitter 
# Imports the interface to convert text into numerical vectors using OpenAI's models
from langchain_openai import OpenAIEmbeddings
# Imports the vector database used to store and efficiently search text embeddings             
from langchain_chroma import Chroma

In [2]:
from dotenv import load_dotenv

load_dotenv()

True

In [3]:
import pandas as pd

books_df = pd.read_csv("../data/processed/book_cleaned.csv")
books_df.head()

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitles,tagged_description
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,NaN,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."

In [4]:
books_df["tagged_description"].head()

0    9780002005883 A NOVEL THAT READERS and critics...
1    9780002261982 A new 'Christie for Christmas' -...
2    9780006178736 A memorable, mesmerizing heroine...
3    9780006280897 Lewis' work on the nature of lov...
4    9780006280934 "In The Problem of Pain, C.S. Le...
Name: tagged_description, dtype: str

In [5]:
# opening a txt for writing the tagged descriptions
with open("../data/processed/tagged_description.txt", "w", encoding="utf-8") as f:
    f.write("\n".join(books_df["tagged_description"].astype(str)))

In [6]:
raw_docs = TextLoader("../data/processed/tagged_description.txt", encoding="utf-8").load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=100, separator="\n")
documents = text_splitter.split_documents(raw_docs)

Created a chunk of size 1168, which is longer than the specified 1000
Created a chunk of size 1214, which is longer than the specified 1000
Created a chunk of size 1088, which is longer than the specified 1000
Created a chunk of size 1189, which is longer than the specified 1000

Created a chunk of size 1253, which is longer than the specified 1000
Created a chunk of size 2006, which is longer than the specified 1000
Created a chunk of size 1222, which is longer than the specified 1000
Created a chunk of size 1184, which is longer than the specified 1000
Created a chunk of size 1214, which is longer than the specified 1000
Created a chunk of size 1191, which is longer than the specified 1000
Created a chunk of size 1057, which is longer than the specified 1000
Created a chunk of size 1270, which is longer than the specified 1000
Created a chunk of size 1635, which is longer than the specified 1000
Created a chunk of size 1128, which is longer than the specified 1000
Created a chunk of size 1319, which is longer than the specified 1000
Created a chunk of size 1119, which is longer than the specified 1000
Created a chunk of size 1189, which is longer than the specified 1000
Created a chunk of size 2008, which is longer than the specified 1000
Created a chunk of size 1286, which is longer than the specified 1000
Created a chunk of size 1225, which is longer than the specified 1000
Created a chunk of size 1236, which is longer than the specified 1000
Created a chunk of size 1126, which is longer than the specified 1000
Created a chunk of size 1073, which is longer than the specified 1000
Created a chunk of size 1318, which is longer than the specified 1000
Created a chunk of size 2826, which is longer than the specified 1000
Created a chunk of size 1141, which is longer than the specified 1000
Created a chunk of size 1004, which is longer than the specified 1000
Created a chunk of size 2504, which is longer than the specified 1000
Created a chunk of size 1422, which is longer than the specified 1000
Created a chunk of size 1083, which is longer than the specified 1000
Created a chunk of size 1144, which is longer than the specified 1000
Created a chunk of size 1262, which is longer than the specified 1000
Created a chunk of size 1086, which is longer than the specified 1000
Created a chunk of size 1812, which is longer than the specified 1000
Created a chunk of size 1826, which is longer than the specified 1000
Created a chunk of size 1060, which is longer than the specified 1000
Created a chunk of size 1180, which is longer than the specified 1000
Created a chunk of size 1284, which is longer than the specified 1000
Created a chunk of size 1642, which is longer than the specified 1000
Created a chunk of size 1930, which is longer than the specified 1000
Created a chunk of size 2000, which is longer than the specified 1000
Created a chunk of size 2281, which is longer than the specified 1000
Created a chunk of size 1142, which is longer than the specified 1000
Created a chunk of size 1137, which is longer than the specified 1000
Created a chunk of size 1086, which is longer than the specified 1000
Created a chunk of size 1479, which is longer than the specified 1000
Created a chunk of size 1135, which is longer than the specified 1000
Created a chunk of size 1032, which is longer than the specified 1000
Created a chunk of size 1015, which is longer than the specified 1000
Created a chunk of size 1088, which is longer than the specified 1000
Created a chunk of size 1912, which is longer than the specified 1000
Created a chunk of size 2608, which is longer than the specified 1000
Created a chunk of size 1574, which is longer than the specified 1000
Created a chunk of size 1524, which is longer than the specified 1000
Created a chunk of size 2030, which is longer than the specified 1000
Created a chunk of size 1612, which is longer than the specified 1000
Created a chunk of size 1189, which is longer than the specified 1000
Created a chunk of size 1282, which is longer than the specified 1000
Created a chunk of size 1262, which is longer than the specified 1000
Created a chunk of size 1271, which is longer than the specified 1000
Created a chunk of size 1056, which is longer than the specified 1000
Created a chunk of size 1159, which is longer than the specified 1000
Created a chunk of size 1054, which is longer than the specified 1000
Created a chunk of size 1078, which is longer than the specified 1000
Created a chunk of size 2750, which is longer than the specified 1000
Created a chunk of size 1033, which is longer than the specified 1000
Created a chunk of size 1004, which is longer than the specified 1000
Created a chunk of size 1064, which is longer than the specified 1000
Created a chunk of size 1224, which is longer than the specified 1000
Created a chunk of size 1805, which is longer than the specified 1000
Created a chunk of size 1013, which is longer than the specified 1000
Created a chunk of size 1262, which is longer than the specified 1000
Created a chunk of size 1767, which is longer than the specified 1000
Created a chunk of size 1266, which is longer than the specified 1000
Created a chunk of size 1011, which is longer than the specified 1000
Created a chunk of size 1177, which is longer than the specified 1000
Created a chunk of size 1715, which is longer than the specified 1000
Created a chunk of size 1677, which is longer than the specified 1000
Created a chunk of size 1128, which is longer than the specified 1000
Created a chunk of size 1997, which is longer than the specified 1000
Created a chunk of size 1171, which is longer than the specified 1000
Created a chunk of size 2123, which is longer than the specified 1000
Created a chunk of size 1316, which is longer than the specified 1000
Created a chunk of size 1112, which is longer than the specified 1000
Created a chunk of size 1316, which is longer than the specified 1000
Created a chunk of size 1121, which is longer than the specified 1000
Created a chunk of size 1018, which is longer than the specified 1000
Created a chunk of size 1007, which is longer than the specified 1000
Created a chunk of size 1057, which is longer than the specified 1000
Created a chunk of size 1251, which is longer than the specified 1000
Created a chunk of size 1098, which is longer than the specified 1000
Created a chunk of size 1143, which is longer than the specified 1000
Created a chunk of size 1550, which is longer than the specified 1000
Created a chunk of size 1652, which is longer than the specified 1000
Created a chunk of size 1495, which is longer than the specified 1000
Created a chunk of size 1277, which is longer than the specified 1000
Created a chunk of size 1046, which is longer than the specified 1000
Created a chunk of size 1666, which is longer than the specified 1000
Created a chunk of size 1616, which is longer than the specified 1000
Created a chunk of size 1095, which is longer than the specified 1000
Created a chunk of size 1597, which is longer than the specified 1000
Created a chunk of size 1960, which is longer than the specified 1000
Created a chunk of size 1708, which is longer than the specified 1000
Created a chunk of size 1947, which is longer than the specified 1000
Created a chunk of size 1021, which is longer than the specified 1000
Created a chunk of size 1807, which is longer than the specified 1000
Created a chunk of size 1518, which is longer than the specified 1000
Created a chunk of size 1087, which is longer than the specified 1000
Created a chunk of size 1093, which is longer than the specified 1000
Created a chunk of size 1163, which is longer than the specified 1000
Created a chunk of size 1259, which is longer than the specified 1000
Created a chunk of size 1480, which is longer than the specified 1000
Created a chunk of size 1037, which is longer than the specified 1000
Created a chunk of size 1085, which is longer than the specified 1000
Created a chunk of size 1443, which is longer than the specified 1000
Created a chunk of size 1266, which is longer than the specified 1000
Created a chunk of size 1144, which is longer than the specified 1000
Created a chunk of size 1369, which is longer than the specified 1000
Created a chunk of size 1622, which is longer than the specified 1000
Created a chunk of size 1165, which is longer than the specified 1000
Created a chunk of size 1176, which is longer than the specified 1000
Created a chunk of size 1179, which is longer than the specified 1000
Created a chunk of size 1009, which is longer than the specified 1000
Created a chunk of size 1022, which is longer than the specified 1000
Created a chunk of size 1357, which is longer than the specified 1000
Created a chunk of size 1172, which is longer than the specified 1000
Created a chunk of size 1394, which is longer than the specified 1000
Created a chunk of size 1216, which is longer than the specified 1000
Created a chunk of size 2203, which is longer than the specified 1000
Created a chunk of size 1371, which is longer than the specified 1000
Created a chunk of size 2873, which is longer than the specified 1000
Created a chunk of size 1269, which is longer than the specified 1000
Created a chunk of size 1708, which is longer than the specified 1000
Created a chunk of size 1638, which is longer than the specified 1000
Created a chunk of size 2398, which is longer than the specified 1000
Created a chunk of size 2120, which is longer than the specified 1000
Created a chunk of size 1488, which is longer than the specified 1000
Created a chunk of size 1691, which is longer than the specified 1000
Created a chunk of size 1418, which is longer than the specified 1000
Created a chunk of size 1165, which is longer than the specified 1000
Created a chunk of size 1353, which is longer than the specified 1000
Created a chunk of size 2171, which is longer than the specified 1000
Created a chunk of size 1093, which is longer than the specified 1000
Created a chunk of size 2167, which is longer than the specified 1000
Created a chunk of size 1454, which is longer than the specified 1000
Created a chunk of size 1454, which is longer than the specified 1000
Created a chunk of size 1973, which is longer than the specified 1000
Created a chunk of size 1975, which is longer than the specified 1000
Created a chunk of size 1640, which is longer than the specified 1000
Created a chunk of size 2709, which is longer than the specified 1000
Created a chunk of size 1632, which is longer than the specified 1000
Created a chunk of size 1284, which is longer than the specified 1000
Created a chunk of size 1478, which is longer than the specified 1000
Created a chunk of size 1049, which is longer than the specified 1000
Created a chunk of size 1003, which is longer than the specified 1000
Created a chunk of size 1150, which is longer than the specified 1000
Created a chunk of size 1208, which is longer than the specified 1000
Created a chunk of size 1028, which is longer than the specified 1000
Created a chunk of size 2452, which is longer than the specified 1000
Created a chunk of size 1343, which is longer than the specified 1000
Created a chunk of size 1267, which is longer than the specified 1000
Created a chunk of size 1117, which is longer than the specified 1000
Created a chunk of size 1544, which is longer than the specified 1000
Created a chunk of size 1191, which is longer than the specified 1000
Created a chunk of size 1160, which is longer than the specified 1000
Created a chunk of size 1145, which is longer than the specified 1000
Created a chunk of size 1014, which is longer than the specified 1000
Created a chunk of size 1774, which is longer than the specified 1000
Created a chunk of size 1161, which is longer than the specified 1000
Created a chunk of size 1009, which is longer than the specified 1000
Created a chunk of size 1017, which is longer than the specified 1000
Created a chunk of size 1323, which is longer than the specified 1000
Created a chunk of size 1213, which is longer than the specified 1000
Created a chunk of size 1123, which is longer than the specified 1000
Created a chunk of size 1594, which is longer than the specified 1000
Created a chunk of size 1957, which is longer than the specified 1000
Created a chunk of size 2442, which is longer than the specified 1000
Created a chunk of size 1796, which is longer than the specified 1000
Created a chunk of size 1562, which is longer than the specified 1000
Created a chunk of size 1219, which is longer than the specified 1000
Created a chunk of size 1380, which is longer than the specified 1000
Created a chunk of size 1448, which is longer than the specified 1000
Created a chunk of size 1102, which is longer than the specified 1000
Created a chunk of size 1298, which is longer than the specified 1000
Created a chunk of size 1761, which is longer than the specified 1000
Created a chunk of size 1004, which is longer than the specified 1000
Created a chunk of size 1022, which is longer than the specified 1000
Created a chunk of size 1064, which is longer than the specified 1000
Created a chunk of size 1009, which is longer than the specified 1000
Created a chunk of size 1058, which is longer than the specified 1000
Created a chunk of size 1625, which is longer than the specified 1000
Created a chunk of size 1587, which is longer than the specified 1000
Created a chunk of size 1579, which is longer than the specified 1000
Created a chunk of size 1259, which is longer than the specified 1000
Created a chunk of size 1128, which is longer than the specified 1000
Created a chunk of size 1099, which is longer than the specified 1000
Created a chunk of size 1076, which is longer than the specified 1000
Created a chunk of size 1529, which is longer than the specified 1000
Created a chunk of size 1202, which is longer than the specified 1000
Created a chunk of size 1093, which is longer than the specified 1000
Created a chunk of size 1247, which is longer than the specified 1000
Created a chunk of size 1050, which is longer than the specified 1000
Created a chunk of size 1211, which is longer than the specified 1000
Created a chunk of size 1011, which is longer than the specified 1000
Created a chunk of size 1352, which is longer than the specified 1000
Created a chunk of size 1412, which is longer than the specified 1000
Created a chunk of size 1023, which is longer than the specified 1000
Created a chunk of size 1216, which is longer than the specified 1000
Created a chunk of size 1131, which is longer than the specified 1000
Created a chunk of size 1187, which is longer than the specified 1000
Created a chunk of size 1891, which is longer than the specified 1000
Created a chunk of size 3168, which is longer than the specified 1000
Created a chunk of size 1532, which is longer than the specified 1000
Created a chunk of size 1588, which is longer than the specified 1000
Created a chunk of size 1605, which is longer than the specified 1000
Created a chunk of size 1623, which is longer than the specified 1000
Created a chunk of size 1419, which is longer than the specified 1000
Created a chunk of size 1114, which is longer than the specified 1000
Created a chunk of size 1128, which is longer than the specified 1000
Created a chunk of size 1036, which is longer than the specified 1000
Created a chunk of size 1139, which is longer than the specified 1000
Created a chunk of size 1178, which is longer than the specified 1000
Created a chunk of size 1048, which is longer than the specified 1000
Created a chunk of size 1211, which is longer than the specified 1000
Created a chunk of size 1161, which is longer than the specified 1000
Created a chunk of size 2020, which is longer than the specified 1000
Created a chunk of size 1115, which is longer than the specified 1000
Created a chunk of size 1436, which is longer than the specified 1000
Created a chunk of size 1109, which is longer than the specified 1000
Created a chunk of size 1062, which is longer than the specified 1000
Created a chunk of size 1461, which is longer than the specified 1000
Created a chunk of size 1428, which is longer than the specified 1000
Created a chunk of size 1326, which is longer than the specified 1000
Created a chunk of size 1717, which is longer than the specified 1000
Created a chunk of size 1526, which is longer than the specified 1000
Created a chunk of size 1647, which is longer than the specified 1000
Created a chunk of size 1579, which is longer than the specified 1000
Created a chunk of size 1642, which is longer than the specified 1000
Created a chunk of size 1687, which is longer than the specified 1000
Created a chunk of size 2031, which is longer than the specified 1000
Created a chunk of size 1107, which is longer than the specified 1000
Created a chunk of size 1043, which is longer than the specified 1000
Created a chunk of size 1118, which is longer than the specified 1000
Created a chunk of size 1089, which is longer than the specified 1000
Created a chunk of size 1095, which is longer than the specified 1000
Created a chunk of size 1124, which is longer than the specified 1000
Created a chunk of size 1338, which is longer than the specified 1000
Created a chunk of size 1080, which is longer than the specified 1000
Created a chunk of size 1163, which is longer than the specified 1000
Created a chunk of size 1003, which is longer than the specified 1000
Created a chunk of size 1075, which is longer than the specified 1000
Created a chunk of size 1226, which is longer than the specified 1000
Created a chunk of size 1235, which is longer than the specified 1000
Created a chunk of size 2940, which is longer than the specified 1000
Created a chunk of size 1118, which is longer than the specified 1000
Created a chunk of size 1490, which is longer than the specified 1000
Created a chunk of size 1157, which is longer than the specified 1000
Created a chunk of size 1208, which is longer than the specified 1000
Created a chunk of size 1485, which is longer than the specified 1000
Created a chunk of size 1082, which is longer than the specified 1000
Created a chunk of size 1792, which is longer than the specified 1000
Created a chunk of size 1595, which is longer than the specified 1000
Created a chunk of size 1026, which is longer than the specified 1000
Created a chunk of size 1349, which is longer than the specified 1000
Created a chunk of size 1631, which is longer than the specified 1000
Created a chunk of size 1376, which is longer than the specified 1000
Created a chunk of size 1763, which is longer than the specified 1000
Created a chunk of size 1971, which is longer than the specified 1000
Created a chunk of size 1228, which is longer than the specified 1000
Created a chunk of size 1104, which is longer than the specified 1000
Created a chunk of size 1047, which is longer than the specified 1000
Created a chunk of size 1119, which is longer than the specified 1000
Created a chunk of size 1127, which is longer than the specified 1000
Created a chunk of size 1033, which is longer than the specified 1000
Created a chunk of size 1280, which is longer than the specified 1000
Created a chunk of size 1471, which is longer than the specified 1000
Created a chunk of size 1260, which is longer than the specified 1000
Created a chunk of size 1214, which is longer than the specified 1000
Created a chunk of size 1003, which is longer than the specified 1000
Created a chunk of size 1037, which is longer than the specified 1000
Created a chunk of size 1052, which is longer than the specified 1000
Created a chunk of size 1017, which is longer than the specified 1000
Created a chunk of size 1177, which is longer than the specified 1000
Created a chunk of size 1246, which is longer than the specified 1000
Created a chunk of size 1049, which is longer than the specified 1000
Created a chunk of size 1125, which is longer than the specified 1000
Created a chunk of size 1123, which is longer than the specified 1000
Created a chunk of size 1025, which is longer than the specified 1000
Created a chunk of size 1290, which is longer than the specified 1000

In [7]:
documents[0]

Document(metadata={'source': '../data/processed/tagged_description.txt'}, page_content='9780002005883 A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.')

In [8]:
db_books = Chroma.from_documents(documents, OpenAIEmbeddings())

In [9]:
query = "A Book to teach children about the importance of kindness"

docs = db_books.similarity_search(query, k=10)
docs

[Document(id='72f3dbec-7cea-4dcf-ac4a-ae9a4986256b', metadata={'source': '../data/processed/tagged_description.txt'}, page_content='9780590956161 When a new boy in his second grade class tries to get the other students to play a game that involves saying the meanest things possible to one another, Little Bill shows him a better way to make friends.\n9780590975001 Summary: Kidnapped from her orphanage by a BFG (Big Friendly Giant), who spends his life blowing happy dreams to children, Sophie concocts with him a plan to save the world from nine other man-gobbling cannibal giants.\n9780590988490 When her father is murdered and the police obtain an e-mail confession that implicates her, Alice Robie realizes she will have to flee and prove her innocence. Original.'),
 Document(id='144869f5-53a6-40eb-9b7f-fbdaf791b144', metadata={'source': '../data/processed/tagged_description.txt'}, page_content="9780941807555 THE LITTLE BIG BOOK FOR GOD'S CHILDREN is a wonderful resource for parents looking to introduce their children to the wisdom and beauty of Christian faith. Illustrated with early twentieth-century art from artists such as Jessie Wilcox Smith, Ellen H. Clapsaddle, and Maud and Miska Petersham, this Little Big Book presents selected bible stories, parables, and verses; poems and prayers; excerpts and fables; songs and hymns; and activities - all collected in one delightful volume. A celebration of God's enduring message of love, GOD'S CHILDREN is sure to provide an endless wellspring of inspiration and hope."),
 Document(id='dba72818-283f-41fb-8ef4-6bbe0bc62b43', metadata={'source': '../data/processed/tagged_description.txt'}, page_content='9780374422080 This Newbery Honor Book tells the story of 11 -year-old Primrose, who lives in a small fishing village in British Columbia. She recounts her experiences and all she learns about human nature and the unpredictability of life after her parents are lost at sea.'),
 Document(id='6c643215-ca59-4ee1-83d8-4776fd014c5a', metadata={'source': '../data/processed/tagged_description.txt'}, page_content="9780064410724 The students' scheme to find a love match for their beloved teacher on Valentine's Day turns into a comedy of errors when four stupid cupids from Ancient Greece try to help.\n9780064410939 Beloved by generations, Charlotte's Web and Stuart Little are two of the most cherished stories of all time. Now, for the first time ever, these treasured classics are available in lavish new collectors' editions. In addition to a larger trim size, the original black-and-white art by Garth Williams has been lovingly colorized by renowned illustrator Rosemary Wells, adding another dimension to these two perfect books for young and old alike."),
 Document(id='2118d6b3-89ea-456c-8bc3-93ea651e23f5', metadata={'source': '../data/processed/tagged_description.txt'}, page_content="9780763621643 As a page in his uncle's castle in thirteenth-century England, eleven-year-old Tobias records in his journal his experiences learning how to hunt, play games of skill, and behave in noble society.\n9780763625894 Edward Tulane, a cold-hearted and proud toy rabbit, loves only himself until he is separated from the little girl who adores him and travels across the country, acquiring new owners and listening to their hopes, dreams, and histories. Jr Lib Guild. Teacher's Guide available. 300,000 first printing.\n9780763626150 Judy is excited about becoming a doctor, especially when Class 3T starts a new unit on the human body, but she learns more about being a patient when she catches tonsillitis from her little brother, Stink. Reprint. 75,000 first printing."),
 Document(id='3a052a44-dce4-412d-a297-ae137edee98a', metadata={'source': '../data/processed/tagged_description.txt'}, page_content='9781590301876 In this inspiring book, Sharon Salzberg, one of America\'s leading spiritual teachers, shows us how the Buddhist path of metta, or lovingkindness, can help us discover the radiant, joyful heart within each of us. The author draws on simple Buddhist teachings, wisdom stories from various traditions, guided meditation practices, and her own experience of practice and teaching to illustrate how each one of us can cultivate love, compassion, joy, and equanimity\'the four "heavenly abodes" of traditional Buddhism.'),
 Document(id='963e30b3-e9b9-40f5-8ac6-95aa3632738f', metadata={'source': '../data/processed/tagged_description.txt'}, page_content='9780060177249 After a mysterious stranger promises to end his boredom with a trip to the magical Holiday House, ten-year-old Harvey learns that his fun has a high price'),
 Document(id='08bc2ef0-d637-4021-8112-0cdbb3fe1299', metadata={'source': '../data/processed/tagged_description.txt'}, page_content="9781561709335 In this groundbreaking book you will learn how to get demonstrably true answers to your questions, and know what true success is and how to create it.\n9781561796779 The authors maintain that children's core values are greatly shaped by what is going on in their culture when they are ten years old--and they show parents how to achieve reconciliation and improve communication between generations.\n9781562549428 In seventeenth-century France, young D'Artagnan initially quarrels with, then befriends, three musketeers and joins them in trying to outwit the enemies of the king and queen.\n9781562802349 Tall, athletic Joanna Kingston has a roguish way about her that draws women like a magnet. Yet, as too many lovers have discovered too late, though Joanna's bedroom door is always open, she keeps her wounded heart under lock and key."),
 Document(id='1c809802-a251-4f5b-8105-a11d2910c084', metadata={'source': '../data/processed/tagged_description.txt'}, page_content="9780590032490 A young boy and his Norwegian grandmother, who is an expert on witches, together foil a witches' plot to destroy the world's children by turning them into mice."),
 Document(id='e0f302c7-7365-4956-ace1-38f8b040d685', metadata={'source': '../data/processed/tagged_description.txt'}, page_content="9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience.\n9780786808373 Introducing your baby to birds, cats, dogs, and babies through fine art, illsutration and photographs. These books are a rare opportunity to expose little ones to a range of images on a single subject, from simple child's drawings and abstract art to playful photos. A brief text accompanies each image, introducing baby to some basic -- and sometimes playful -- information on the subjects.")]

In [11]:
books_df[books_df["isbn13"]==int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitles,tagged_description
2870,9780590956161,0590956167,The Meanest Thing to Say,NaN,Bill Cosby;Varnette P. Honeywood,Juvenile Fiction,http://books.google.com/books/content?id=BCaaN...,When a new boy in his second grade class tries...,1997.0,3.53,40.0,956.0,The Meanest Thing to Say,9780590956161 When a new boy in his second gra...

In [12]:
# Creating a function that perform search and pull book details
def retrive_semantic_recomendations(query: str, k: int = 10) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k=k)
    book_list = []

    for  i in range(0, len(recs)):
        book_list += [int(recs[i].page_content.split()[0])]

    return books_df[books_df["isbn13"].isin(book_list)]

In [13]:
retrive_semantic_recomendations("a book about pirates")

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitles,tagged_description
198,9780060733353,0060733357,The Confusion,Volume Two of The Baroque Cycle,Neal Stephenson,Fiction,http://books.google.com/books/content?id=NJbll...,"In the year 1689, a cabal of Barbary galley sl...",2005.0,4.25,815.0,18790.0,The Confusion: Volume Two of The Baroque Cycle,"9780060733353 In the year 1689, a cabal of Bar..."
1074,9780237525378,0237525372,Oliver Twist,NaN,Pauline Francis;Charles Dickens,Juvenile Nonfiction,http://books.google.com/books/content?id=X6RvT...,This wonderful series is a quick way into a ra...,2003.0,3.66,48.0,92.0,Oliver Twist,9780237525378 This wonderful series is a quick...
2066,9780425205594,0425205592,Dark Watch,NaN,Clive Cussler;Jack B. Du Brul,Fiction,http://books.google.com/books/content?id=EKDrH...,When Japanese shipping magnates whose fortunes...,2005.0,4.09,357.0,5749.0,Dark Watch,9780425205594 When Japanese shipping magnates ...
3539,9780755323012,0755323017,The Death Ship of Dartmouth,NaN,Michael Jecks,Fiction,http://books.google.com/books/content?id=yVArA...,When a body is found lying in the middle of th...,2006.0,4.07,352.0,7.0,The Death Ship of Dartmouth,9780755323012 When a body is found lying in th...
3967,9780812552843,0812552849,The Fourth Book of Lost Swords,Farslayer's Story,Fred Saberhagen,Fiction,http://books.google.com/books/content?id=B_hiW...,"Black Pearl, a mermaid, Cosmos, her treacherou...",1990.0,3.83,252.0,1736.0,The Fourth Book of Lost Swords: Farslayer's Story,"9780812552843 Black Pearl, a mermaid, Cosmos, ..."
4440,9781402714573,1402714572,Treasure Island,NaN,Robert Louis Stevenson,Juvenile Fiction,http://books.google.com/books/content?id=UUl7Z...,While going through the possessions of a decea...,2004.0,3.83,213.0,393.0,Treasure Island,9781402714573 While going through the possessi...
4444,9781402726002,1402726007,The Adventures of Huckleberry Finn,NaN,Mark Twain,Juvenile Fiction,http://books.google.com/books/content?id=pi1gC...,"A nineteenth-century boy, floating down the Mi...",2006.0,3.81,305.0,350.0,The Adventures of Huckleberry Finn,"9781402726002 A nineteenth-century boy, floati..."
4507,9781416535522,1416535527,Santa Cruise,A Holiday Mystery at Sea,Mary Higgins Clark;Carol Higgins Clark,Fiction,http://books.google.com/books/content?id=QsbYE...,Embarking on a Mystery Seminar luxury cruise d...,2006.0,3.41,261.0,4631.0,Santa Cruise: A Holiday Mystery at Sea,9781416535522 Embarking on a Mystery Seminar l...
4545,9781423100188,1423100182,Pirates of the Caribbean: The Coming Storm - J...,Junior Novel,Rob Kidd,Juvenile Fiction,http://books.google.com/books/content?id=UkvjA...,Teenage stowaway Jack Sparrow and his band of ...,2006.0,3.83,135.0,1364.0,Pirates of the Caribbean: The Coming Storm - J...,9781423100188 Teenage stowaway Jack Sparrow an...
4550,9781423101680,1423101685,Pirates of the Caribbean: Age of Bronze - Jack...,NaN,Rob Kidd,Juvenile Fiction,http://books.google.com/books/content?id=iHKIN...,The beginning of a new story arc! Jack and com...,2006.0,4.05,144.0,532.0,Pirates of the Caribbean: Age of Bronze - Jack...,9781423101680 The beginning of a new story arc...